"use client";

import * as React from "react";
import { FileText, Loader2, Printer, Sparkles } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AiBadge } from "@/components/shared/demo-badge";
import type { ReportSection } from "@/lib/services/report";

export function ReportGenerator({
  sections,
  period,
}: {
  sections: ReportSection[];
  period: string;
}) {
  const [state, setState] = React.useState<"idle" | "generating" | "ready">("idle");

  const generate = () => {
    setState("generating");
    setTimeout(() => setState("ready"), 900);
  };

  if (state !== "ready") {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center gap-4 py-16 text-center">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary">
            <FileText className="h-6 w-6" />
          </div>
          <div>
            <p className="text-lg font-semibold">Weekly Business Review</p>
            <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">
              Generate an AI-assembled executive review of the week: performance, pipeline,
              team, account health, market, risks, and priorities for next week.
            </p>
          </div>
          <Button size="lg" onClick={generate} disabled={state === "generating"}>
            {state === "generating" ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> Generating review…
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" /> Generate Weekly Review
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <AiBadge label="AI-generated" />
          <span className="text-sm text-muted-foreground">Week ending {period}</span>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Printer className="h-4 w-4" /> Print / Save PDF
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setState("idle")}>
            Regenerate
          </Button>
        </div>
      </div>

      <Card>
        <CardContent className="prose-sm max-w-none space-y-6 py-6">
          {sections.map((s) => (
            <section key={s.title}>
              <h3 className="mb-2 border-b border-border pb-1 text-base font-semibold">{s.title}</h3>
              <ul className="space-y-1.5">
                {s.body.map((b, i) => (
                  <li key={i} className="flex gap-2 text-sm text-foreground/90">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-muted-foreground" />
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </section>
          ))}
          <p className="border-t border-border pt-3 text-xs text-muted-foreground">
            Generated by Regional360 from in-app demo data. Figures are illustrative;
            PDF export uses your browser&apos;s print dialog in this MVP.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
